import { ArrowRight, Boxes, CheckCircle2, Cpu, FileCode2, Lightbulb, AlertTriangle } from 'lucide-react';
const text=(x,keys,f='')=>typeof x==='string'?x:(keys.find(k=>x?.[k])?x[keys.find(k=>x?.[k])]:f);

export function TechStack({items=[]}) { return <section className="panel"><div className="heading"><span>Technology stack</span><h2>Detected technologies</h2></div><div className="chips">{items.length?items.map((x,i)=><div className="chip" key={i}><Cpu size={14}/>{typeof x==='string'?x:(x.name||x.technology||x.framework||'Unknown')}{x?.category&&<small>{x.category}</small>}</div>):<p className="muted">No technologies returned.</p>}</div></section> }

export function Architecture({data={}}) { const steps=Array.isArray(data)?data:(data.flow||data.layers||[data.type||data.pattern].filter(Boolean)); const shown=steps.length?steps:['Frontend','API','Services','Data Layer']; return <section className="panel"><div className="heading"><span>Architecture</span><h2>How the project is organized</h2></div><div className="flow">{shown.map((x,i)=><div className="flow-wrap" key={i}><div className="node"><Boxes size={16}/>{String(x)}</div>{i<shown.length-1&&<ArrowRight size={17}/>}</div>)}</div>{data.description&&<p className="muted">{data.description}</p>}</section> }

export function Strengths({items=[]}) { return <section className="panel"><div className="heading"><span>Strengths</span><h2>What looks good</h2></div><div className="list">{items.length?items.map((x,i)=><article className="row positive" key={i}><CheckCircle2 size={18}/><div><b>{text(x,['title','name'],'Positive finding')}</b><p>{text(x,['description','evidence','detail'],'')}</p></div></article>):<p className="muted">No strengths returned.</p>}</div></section> }

export function Components({items=[]}) { return <section className="panel"><div className="heading"><span>Key components</span><h2>Important project areas</h2></div><div className="list">{items.length?items.map((x,i)=><article className="row" key={i}><FileCode2 size={18}/><div><b>{text(x,['name','file','path'],'Component')}</b>{x?.file&&<code>{x.file}</code>}<p>{text(x,['description','purpose','role'],'')}</p></div></article>):<p className="muted">No key components returned.</p>}</div></section> }

export function Issues({items=[]}) { return <section className="panel wide"><div className="heading"><span>Risk review</span><h2>Issues & recommendations</h2></div><div className="issues">{items.length?items.map((x,i)=>{const sev=String(x?.severity||'medium').toLowerCase(); const ev=Array.isArray(x?.evidence)?x.evidence.join(' • '):x?.evidence; return <article className="issue" key={i}><div className="issue-top"><span className={`severity ${sev}`}>{sev}</span>{x?.file&&<code>{x.file}</code>}</div><h3>{text(x,['title','name'],'Detected issue')}</h3>{x?.description&&<p>{x.description}</p>}{ev&&<div className="evidence"><AlertTriangle size={14}/>{ev}</div>}{x?.recommendation&&<div className="advice"><Lightbulb size={14}/>{x.recommendation}</div>}</article>}):<p className="muted">No issues returned.</p>}</div></section> }

export function Recommendations({items=[]}) { return <section className="panel wide"><div className="heading"><span>Action plan</span><h2>Prioritized recommendations</h2></div><div className="recommendations">{items.length?items.map((x,i)=><article className="recommendation" key={i}><span className="num">{i+1}</span><div><b>{typeof x==='string'?x:(x.title||'Recommendation')}</b>{x?.priority&&<em>{x.priority}</em>}{x?.description&&<p>{x.description}</p>}</div></article>):<p className="muted">No recommendations returned.</p>}</div></section> }
